## 演習問題

In [1]:
import numpy as np
np.__version__

'1.19.1'

In [2]:
matrix = np.array(
    [43,    57,     22,     80,     8,      86,     99,     56,     88,
    26,     67,     92,     44,     92,     2,      9,      70,     4,
    62,     18,     95,     23,     54,     54,     84,     64,     23,
    68,     91,     59,     41,     78,     5,      73,     12,     38,
    8,      64,     53,     86,     53,     41,     7,      63,     25,
    9,      16,     83,     95,     12,     95,     24,     2,      58,
    86,     39,     7,      79,     80,     19,     79,     97,     24,
    51,     85,     28,     57,     56,     17,     74,     87,     4,
    8,      66,     59,     15,     48,     8,      77,     92,     58]
).reshape(-1,9)
matrix

array([[43, 57, 22, 80,  8, 86, 99, 56, 88],
       [26, 67, 92, 44, 92,  2,  9, 70,  4],
       [62, 18, 95, 23, 54, 54, 84, 64, 23],
       [68, 91, 59, 41, 78,  5, 73, 12, 38],
       [ 8, 64, 53, 86, 53, 41,  7, 63, 25],
       [ 9, 16, 83, 95, 12, 95, 24,  2, 58],
       [86, 39,  7, 79, 80, 19, 79, 97, 24],
       [51, 85, 28, 57, 56, 17, 74, 87,  4],
       [ 8, 66, 59, 15, 48,  8, 77, 92, 58]])

In [3]:
block_size = 3

In [4]:
result = np.empty([block_size, block_size])
for x in range(block_size):
    for y in range(block_size):
        sub_mat = matrix[(x*3):(x+1)*3,(y*3):(y+1)*3]
        result[x,y] = np.mean(sub_mat)
result

array([[53.55555556, 49.22222222, 55.22222222],
       [50.11111111, 56.22222222, 33.55555556],
       [47.66666667, 42.11111111, 65.77777778]])

In [5]:
for x in range(block_size):
    for y in range(block_size):
        print("{:8.2f}".format(result[x,y]), end="")
    print()

   53.56   49.22   55.22
   50.11   56.22   33.56
   47.67   42.11   65.78


### numpyの表示オプションを変更する裏技

In [6]:
# numpyの表示オプションには以下がある
np.get_printoptions()

{'edgeitems': 3,
 'threshold': 1000,
 'floatmode': 'maxprec',
 'precision': 8,
 'suppress': False,
 'linewidth': 75,
 'nanstr': 'nan',
 'infstr': 'inf',
 'sign': '-',
 'formatter': None,
 'legacy': False}

In [7]:
# formatterを設定することで表示桁数を指定できる
#   変数がnumpy.float型である場合のprintすべてに影響するので注意
#   実際、ここ以降のコードでは小数点以下2桁しか表示されていない
np.set_printoptions(formatter={'float': '{:8.2f}'.format})

In [8]:
# オプションを設定したらprintするだけ
print(result)

[[   53.56    49.22    55.22]
 [   50.11    56.22    33.56]
 [   47.67    42.11    65.78]]


## 発展問題

In [9]:
result = np.empty([block_size, block_size])

### np.meanの場合

In [10]:
%%timeit
# google colabでは問題ないのだが、jupyterでは%%timeitはセルの最初の行に書かないとダメ
for x in range(block_size):
    for y in range(block_size):
        result[x,y] = np.mean(matrix[(x*3):(x+1)*3,(y*3):(y+1)*3])

77.5 µs ± 669 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [11]:
result

array([[   53.56,    49.22,    55.22],
       [   50.11,    56.22,    33.56],
       [   47.67,    42.11,    65.78]])

### for文の場合
任意のblock_sizeで動くように全部for文で書くとこうなる

In [12]:
%%timeit
result = np.zeros([block_size, block_size])
for x in range(block_size):
    for y in range(block_size):
        sub_mat = matrix[(x*3):(x+1)*3,(y*3):(y+1)*3]
        for i in range(block_size):
            for j in range(block_size):
                result[x,y] += sub_mat[i,j]
        result[x,y] /= block_size**2

64.6 µs ± 880 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [13]:
result

array([[   53.56,    49.22,    55.22],
       [   50.11,    56.22,    33.56],
       [   47.67,    42.11,    65.78]])

### for文を全く使わない場合

In [14]:
matrix

array([[43, 57, 22, 80,  8, 86, 99, 56, 88],
       [26, 67, 92, 44, 92,  2,  9, 70,  4],
       [62, 18, 95, 23, 54, 54, 84, 64, 23],
       [68, 91, 59, 41, 78,  5, 73, 12, 38],
       [ 8, 64, 53, 86, 53, 41,  7, 63, 25],
       [ 9, 16, 83, 95, 12, 95, 24,  2, 58],
       [86, 39,  7, 79, 80, 19, 79, 97, 24],
       [51, 85, 28, 57, 56, 17, 74, 87,  4],
       [ 8, 66, 59, 15, 48,  8, 77, 92, 58]])

In [15]:
%%timeit
sub_mats = matrix.reshape(-1,3,3).transpose(1,0,2).reshape(-1,3,3)
result = np.mean(sub_mats, axis=(1,2)).reshape(-1,3).T

12.5 µs ± 84.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [16]:
result

array([[   53.56,    49.22,    55.22],
       [   50.11,    56.22,    33.56],
       [   47.67,    42.11,    65.78]])

### こっちの方が速いかも？

In [17]:
%%timeit
# 行列を代入しないで直接平均値を計算して結果を代入
result = matrix.reshape(-1,3,3,3).transpose(0,2,1,3).mean(axis=(2,3))

10.6 µs ± 55.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [18]:
result

array([[   53.56,    49.22,    55.22],
       [   50.11,    56.22,    33.56],
       [   47.67,    42.11,    65.78]])