## 演習問題

In [1]:
# 演習問題からコピペした画像データ
img_data = np.array([
    [204,187,204,204,221,221,221,238,238,255,255,238,204,170,170,187,204,204,204,204,204,204,187,187],
    [153,153,136,136,153,170,170,170,170,187,204,170,153,153,153,170,170,170,187,187,187,187,170,170],
    [153,153,153,136,136,153,153,153,170,170,170,170,153,153,153,153,153,153,153,153,153,153,153,153],
    [153,153,153,153,153,153,153,153,153,153,153,153,153,153,136,136,136,153,153,153,153,153,153,153],
    [153,153,153,170,170,170,187,187,187,221,238,221,187,170,170,170,170,170,170,170,170,170,170,170],
    [170,170,170,170,170,170,153,170,187,221,255,238,187,170,170,170,170,170,170,170,170,170,153,153],
    [170,170,170,170,170,136,102,119,136,153,204,204,170,136,68,68,68,136,136,153,153,153,153,153],
    [153,153,170,153,153,119,17,34,34,34,34,51,68,51,34,51,51,51,51,68,68,85,102,102],
    [136,153,102,34,34,17,17,0,17,34,34,34,34,51,51,34,51,34,51,68,68,68,68,68],
    [51,51,51,17,0,17,34,34,34,34,34,34,34,34,34,51,34,34,34,34,34,51,51,34],
    [17,34,34,34,51,51,51,51,34,51,34,34,34,51,51,51,51,51,34,34,34,34,17,17],
    [51,51,51,68,51,51,51,51,51,51,68,51,51,68,51,51,34,34,34,34,34,17,17,34],
    [51,51,51,51,34,34,34,34,34,51,34,34,34,34,34,34,34,34,51,51,34,51,51,51],
    [34,34,51,34,34,51,51,34,34,34,34,34,51,51,34,51,51,51,51,51,51,51,51,34],
    [34,34,51,34,34,34,34,34,51,51,51,51,51,51,51,34,34,34,34,34,34,34,34,17],
    [34,34,51,68,51,51,51,51,51,51,68,68,68,51,51,51,51,51,34,34,34,17,17,34],
    [34,51,51,68,51,34,17,17,17,17,34,34,34,34,34,34,51,51,51,51,51,34,34,34],
    [51,34,34,51,68,85,51,17,17,17,0,0,17,17,17,17,17,17,34,34,34,34,51,34],
], dtype=np.uint8)

In [2]:
def smooth_image(block_size, block_loc, img):
    topx = block_loc[0]
    topy = block_loc[1]
    # x, yそれぞれについて(topx, topy)の位置からblock_size分を取り出し、
    # すべてを平均して、整数にして返却
    # intの代わりにnp.roundなどを使っても良い（結果は変わるけど・・・）
    return int(np.mean(img[topx:topx+block_size, topy:topy+block_size]))

### いくつか取り出して試してみる

In [3]:
print(smooth_image(3, [0,0], img_data))
# データを見ながら手動で計算
(204+187+204 + 153+153+136 + 153+153+153) / 9

166


166.22222222222223

In [4]:
print(smooth_image(3, [2,1], img_data))
(153+153+136 + 153+153+153 + 153+153+170) / 9

153


153.0

### 全データに適用

In [5]:
block_size = 3

In [6]:
# 結果格納用の変数を用意
#   用意しなくてもいいが、用意した方が速く動作する
#   img_dataのx, yをそれぞれblock_sizeで除したものが平均後のサイズ
result = np.empty((np.array(img_data.shape) / block_size).astype(np.int), dtype=np.uint8)

# x, yは結果格納用変数のサイズでloop
for x in range(result.shape[0]):
    for y in range(result.shape[1]):
        # あとは位置を指定してsmooth_imageを呼び出すだけ
        result[x,y] = smooth_image(block_size, [x*block_size,y*block_size], img_data)

print(result)

[[166 170 187 202 162 173 181 173]
 [158 164 170 205 166 160 164 160]
 [153 109  52  86  73  60  90 105]
 [ 43  37  43  43  45  43  34  30]
 [ 43  37  37  41  43  39  43  41]
 [ 41  58  32  32  35  37  39  32]]


## 発展問題

In [7]:
def smooth_image_ext(block_size, block_loc, img):
    topx = block_loc[0]
    topy = block_loc[1]

    # 画像サイズ外の場所を指定されたらエラー
    if topx < 0 or topy < 0 or topx >= img.shape[0] or topy >= img.shape[1]:
        return np.nan

    # 画像の端ではみ出す場合は端を基準にする
    # 右端
    if topx + block_size >= img.shape[0]:
        topx = img.shape[0] - block_size
    # 下端
    if topy + block_size >= img.shape[1]:
        topy = img.shape[1] - block_size

    # 平均化処理は演習問題と同じ，intの代わりにnp.roundなどを使っても良い（結果は変わるけど・・・）
    return int(np.mean(img[topx:topx+block_size, topy:topy+block_size]))

### いくつか取り出して試してみる

In [8]:
print(smooth_image_ext(4, [12,20], img_data))

37


In [9]:
print(img_data[12:16,20:24])
np.mean(img_data[12:16,20:24])

[[34 51 51 51]
 [51 51 51 34]
 [34 34 34 17]
 [34 17 17 34]]


37.1875

In [10]:
smooth_image_ext(4, [0,0], img_data)

161

In [11]:
print(img_data[0:4,0:4])
np.mean(img_data[0:4,0:4])

[[204 187 204 204]
 [153 153 136 136]
 [153 153 153 136]
 [153 153 153 153]]


161.5

### 全体に適用

#### block_size = 4のとき

In [12]:
block_size = 4
result = np.empty((np.ceil(np.array(img_data.shape) / block_size)).astype(np.int), dtype=np.uint8)
for x in range(result.shape[0]):
    for y in range(result.shape[1]):
        result[x,y] = smooth_image_ext(block_size, [x*block_size,y*block_size], img_data)
print(result)

[[161 173 188 159 171 170]
 [163 139 163 127 129 143]
 [ 58  35  39  45  40  40]
 [ 43  40  45  45  42  37]
 [ 44  42  36  38  38  32]]


#### block_size = 5のとき

In [13]:
block_size = 5
result = np.empty((np.ceil(np.array(img_data.shape) / block_size)).astype(np.int), dtype=np.uint8)
for x in range(result.shape[0]):
    for y in range(result.shape[1]):
        result[x,y] = smooth_image_ext(block_size, [x*block_size,y*block_size], img_data)
print(result)

[[161 182 176 169 170]
 [124  80  96  84 102]
 [ 42  43  44  41  36]
 [ 44  38  39  40  36]]
